# Generated by Django 4.0.3 on 2022-04-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0002_alter_measurement_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='name',
            new_name='sensor_name',
        ),
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(max_length=60, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
